@startuml
package "SI" #DDDDDD {

    map Practitioner {
        id => Internal id of the practitioner
        irisDpId=> IrisDp id of the practitioner (used for update, relations...)
        rpps => The RPPS number
    }

   map PractitionerQualification{
        practitionerId => Internal id of the practitioner
        qualificationId => Internal id of the qualification
   }

    map Qualification {
        id => Internal id of the qualification
        system => System of the Qualification (ex: TRE-49)
        code => Code of the Qualificiation
        label => Label of the Qualification
    }

    Practitioner -- PractitionerQualification
    PractitionerQualification -- Qualification

    note right of PractitionerQualification
        Store the relation between Qualification and Practitioner
    end note




    note right of Qualification
        All qualifications
        You can get all available qualification from our repositories (*)
    end note

    skinparam map{
        backgroundColor #1d71b8
        textColor #fff
        FontColor #ffffff
    }

    skinparam note{
        backgroundColor #d20050
        textColor #fff
        FontColor #ffffff
    }
}
@enduml